# Generated by Django 2.0.5 on 2019-06-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ddr', models.IntegerField()),
                ('screen_size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ppi', models.IntegerField()),
                ('system', models.CharField(max_length=128)),
                ('memory', models.IntegerField()),
                ('camera_resolution', models.DecimalField(decimal_places=1, max_digits=3)),
                ('double_camera', models.BooleanField()),
                ('bluetooth_version', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneApple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apple_id', models.BooleanField()),
                ('face_id', models.BooleanField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.Phone')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneSamsung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stylus', models.BooleanField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.Phone')),
            ],
        ),
    ]
