# Generated by Django 2.0.5 on 2019-06-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='brand',
            field=models.CharField(default='samsung', max_length=128),
            preserve_default=False,
        ),
    ]
