# Generated by Django 2.2.2 on 2019-06-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190622_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='badges',
            new_name='scopes',
        ),
        migrations.RenameField(
            model_name='articlebadge',
            old_name='badge',
            new_name='topic',
        ),
    ]
