# Generated by Django 2.2.2 on 2019-06-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190622_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='name',
            new_name='topic',
        ),
    ]
