# Generated by Django 2.2.2 on 2019-06-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190622_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlebadge',
            old_name='is_mane',
            new_name='is_main',
        ),
    ]
