# Generated by Django 2.2.2 on 2019-06-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameinfo',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
