# Generated by Django 2.2.2 on 2019-06-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergameinfo',
            name='is_host',
        ),
    ]
